import type { AssistanceDistribution } from '@/types';

export const TOTAL_DISTRIBUTIONS = 352;
export const TOTAL_BENEFICIARIES = 1245;
export const TOTAL_AMOUNT_DISTRIBUTED = 2_456_750;
export const DISTRIBUTIONS_THIS_MONTH = 28;
export const COMPLETED_THIS_YEAR = 298;

export const DISTRIBUTIONS: AssistanceDistribution[] = [
  {
    id: '1',
    distributionCode: 'DIST-0001',
    programName: 'Seed & Fertilizer Program',
    programIcon: 'sprout',
    farmerName: 'Juan Dela Cruz',
    contactNumber: '0917 123 4567',
    barangay: 'San Isidro',
    assistanceType: 'Fertilizer',
    quantityLabel: '5 bags (50kg)',
    amountPeso: 2500,
    distributedAt: '2025-05-05',
    status: 'completed',
    distributedBy: 'Agriculture Officer',
  },
  {
    id: '2',
    distributionCode: 'DIST-0002',
    programName: 'Rice Seed Subsidy',
    programIcon: 'seeds',
    farmerName: 'Maria Santos',
    contactNumber: '0920 987 6543',
    barangay: 'San Roque',
    assistanceType: 'Inbred Rice Seeds',
    quantityLabel: '2 cavans',
    amountPeso: 1800,
    distributedAt: '2025-05-08',
    status: 'completed',
    distributedBy: 'Barangay Official',
  },
  {
    id: '3',
    distributionCode: 'DIST-0003',
    programName: 'Livestock Support',
    programIcon: 'livestock',
    farmerName: 'Jose Rizal',
    contactNumber: '0935 246 8101',
    barangay: 'Poblacion',
    assistanceType: 'Feeds',
    quantityLabel: '3 sacks',
    amountPeso: 4200,
    distributedAt: '2025-05-10',
    status: 'pending',
    distributedBy: 'Agriculture Officer',
  },
  {
    id: '4',
    distributionCode: 'DIST-0004',
    programName: 'Corn Production Aid',
    programIcon: 'wheat',
    farmerName: 'Pedro Garcia',
    contactNumber: '0918 765 4321',
    barangay: 'Mabini',
    assistanceType: 'Hybrid Corn Seeds',
    quantityLabel: '1 pack',
    amountPeso: 3200,
    distributedAt: '2025-05-12',
    status: 'completed',
    distributedBy: 'Barangay Official',
  },
  {
    id: '5',
    distributionCode: 'DIST-0005',
    programName: 'Seed & Fertilizer Program',
    programIcon: 'sprout',
    farmerName: 'Ana Reyes',
    contactNumber: '0927 135 7924',
    barangay: 'San Isidro',
    assistanceType: 'Organic Fertilizer',
    quantityLabel: '4 bags (40kg)',
    amountPeso: 2100,
    distributedAt: '2025-05-14',
    status: 'cancelled',
    distributedBy: 'Agriculture Officer',
  },
  {
    id: '6',
    distributionCode: 'DIST-0006',
    programName: 'Animal Feed Assistance',
    programIcon: 'feeds',
    farmerName: 'Lito Romano',
    contactNumber: '0932 456 7890',
    barangay: 'San Roque',
    assistanceType: 'Feeds',
    quantityLabel: '2 sacks',
    amountPeso: 2800,
    distributedAt: '2025-05-16',
    status: 'pending',
    distributedBy: 'Barangay Official',
  },
  {
    id: '7',
    distributionCode: 'DIST-0007',
    programName: 'Rice Seed Subsidy',
    programIcon: 'seeds',
    farmerName: 'Celia Mendoza',
    contactNumber: '0916 864 2097',
    barangay: 'Mabini',
    assistanceType: 'Inbred Rice Seeds',
    quantityLabel: '3 cavans',
    amountPeso: 2700,
    distributedAt: '2025-05-18',
    status: 'completed',
    distributedBy: 'Agriculture Officer',
  },
  {
    id: '8',
    distributionCode: 'DIST-0008',
    programName: 'Vegetable Seeds Program',
    programIcon: 'sprout',
    farmerName: 'Benito Silva',
    contactNumber: '0919 333 4444',
    barangay: 'Poblacion',
    assistanceType: 'Vegetable Seeds',
    quantityLabel: '6 packets',
    amountPeso: 950,
    distributedAt: '2025-05-20',
    status: 'completed',
    distributedBy: 'Barangay Official',
  },
];
