import type { DocumentSubmission } from '@/types';

export const TOTAL_SUBMISSIONS = 93;
export const PENDING_REVIEW = 18;
export const VERIFIED_THIS_MONTH = 64;
export const REJECTED_THIS_MONTH = 7;
export const NEEDS_REVISION = 4;

export const DOCUMENT_SUBMISSIONS: DocumentSubmission[] = [
  {
    id: '1',
    submissionCode: 'DOC-0093',
    farmerId: '1',
    farmerName: 'Juan Dela Cruz',
    farmerRegistryId: 'FRM-2025-000124',
    barangay: 'San Isidro',
    documentType: 'Land Title',
    linkedTo: 'Farmer Registration',
    fileName: 'land_title_juan_delacruz.pdf',
    submittedAt: '2025-05-22T08:30:00',
    submittedBy: 'Farmer (self-service)',
    status: 'pending',
  },
  {
    id: '2',
    submissionCode: 'DOC-0092',
    farmerId: '5',
    farmerName: 'Ana Reyes',
    farmerRegistryId: 'FRM-2025-000005',
    barangay: 'San Isidro',
    documentType: 'Barangay Clearance',
    linkedTo: 'Assistance Program Enrollment',
    fileName: 'brgy_clearance_ana_reyes.jpg',
    submittedAt: '2025-05-21T15:10:00',
    submittedBy: 'Barangay Official',
    status: 'under_review',
  },
  {
    id: '3',
    submissionCode: 'DOC-0091',
    farmerId: '3',
    farmerName: 'Jose Rizal',
    farmerRegistryId: 'FRM-2025-000003',
    barangay: 'Poblacion',
    documentType: 'Tax Declaration',
    linkedTo: 'Land Parcel Update',
    fileName: 'tax_dec_2025_jose_rizal.pdf',
    submittedAt: '2025-05-21T10:45:00',
    submittedBy: 'Field Enumerator',
    status: 'pending',
  },
  {
    id: '4',
    submissionCode: 'DOC-0090',
    farmerId: '4',
    farmerName: 'Pedro Garcia',
    farmerRegistryId: 'FRM-2025-000004',
    barangay: 'Mabini',
    documentType: 'Land ID / Sketch',
    linkedTo: 'Farm Land Registration',
    fileName: 'farm_sketch_pedro_garcia.png',
    submittedAt: '2025-05-20T14:20:00',
    submittedBy: 'Agriculture Officer',
    status: 'needs_revision',
    reviewedBy: 'Maria Santos',
    reviewedAt: '2025-05-20T16:00:00',
    rejectionReason: 'Sketch missing boundary markers on north side',
  },
  {
    id: '5',
    submissionCode: 'DOC-0089',
    farmerId: '2',
    farmerName: 'Maria Santos',
    farmerRegistryId: 'FRM-2025-000002',
    barangay: 'San Roque',
    documentType: 'Valid ID',
    linkedTo: 'Farmer Registration',
    fileName: 'philsys_id_maria_santos.jpg',
    submittedAt: '2025-05-19T09:00:00',
    submittedBy: 'Farmer (self-service)',
    status: 'verified',
    reviewedBy: 'Maria Santos',
    reviewedAt: '2025-05-19T11:30:00',
  },
  {
    id: '6',
    submissionCode: 'DOC-0088',
    farmerId: '6',
    farmerName: 'Lito Romano',
    farmerRegistryId: 'FRM-2025-000006',
    barangay: 'San Roque',
    documentType: 'RSBSA Form',
    linkedTo: 'Farmer Registration',
    fileName: 'rsbsa_form_lito_romano.pdf',
    submittedAt: '2025-05-18T13:25:00',
    submittedBy: 'Field Enumerator',
    status: 'verified',
    reviewedBy: 'Barangay Official',
    reviewedAt: '2025-05-18T15:00:00',
  },
  {
    id: '7',
    submissionCode: 'DOC-0087',
    farmerId: '8',
    farmerName: 'Benito Silva',
    farmerRegistryId: 'FRM-2025-000008',
    barangay: 'Poblacion',
    documentType: 'Farm Photo',
    linkedTo: 'Crop & Harvest Record',
    fileName: 'farm_plot_benito_silva.jpg',
    submittedAt: '2025-05-17T11:40:00',
    submittedBy: 'Agriculture Officer',
    status: 'rejected',
    reviewedBy: 'Maria Santos',
    reviewedAt: '2025-05-17T14:10:00',
    rejectionReason: 'Image too blurry; please resubmit with daylight photo',
  },
  {
    id: '8',
    submissionCode: 'DOC-0086',
    farmerId: '7',
    farmerName: 'Celia Mendoza',
    farmerRegistryId: 'FRM-2025-000007',
    barangay: 'Mabini',
    documentType: 'Land Title',
    linkedTo: 'Document Verification Queue',
    fileName: 'tct_celia_mendoza.pdf',
    submittedAt: '2025-05-16T08:15:00',
    submittedBy: 'Farmer (self-service)',
    status: 'pending',
  },
  {
    id: '9',
    submissionCode: 'DOC-0085',
    farmerId: '9',
    farmerName: 'Rosalinda Luna',
    farmerRegistryId: 'FRM-2025-000009',
    barangay: 'San Isidro',
    documentType: 'Barangay Clearance',
    linkedTo: 'Seed Distribution',
    fileName: 'clearance_rosalinda_luna.pdf',
    submittedAt: '2025-05-15T16:50:00',
    submittedBy: 'Barangay Official',
    status: 'under_review',
  },
  {
    id: '10',
    submissionCode: 'DOC-0084',
    farmerId: '10',
    farmerName: 'Danilo Valdez',
    farmerRegistryId: 'FRM-2025-000010',
    barangay: 'San Roque',
    documentType: 'Tax Declaration',
    linkedTo: 'Farmer Registration',
    fileName: 'tax_declaration_danilo.pdf',
    submittedAt: '2025-05-14T10:05:00',
    submittedBy: 'Field Enumerator',
    status: 'verified',
    reviewedBy: 'Agriculture Officer',
    reviewedAt: '2025-05-14T12:20:00',
  },
];
