import type { ApprovalTransaction } from '@/types';

export const TOTAL_TRANSACTIONS = 86;
export const PENDING_APPROVALS = 14;
export const APPROVED_THIS_MONTH = 52;
export const REJECTED_THIS_MONTH = 8;

export const TRANSACTIONS: ApprovalTransaction[] = [
  {
    id: '1',
    transactionCode: 'TXN-0041',
    type: 'Assistance Distribution',
    farmerName: 'Juan Dela Cruz',
    barangay: 'San Isidro',
    subject: 'Seed & Fertilizer Program',
    details: '5 bags organic fertilizer — pending barangay release',
    amountPeso: 2500,
    submittedAt: '2025-05-22T09:15:00',
    submittedBy: 'Agriculture Officer',
    status: 'pending',
  },
  {
    id: '2',
    transactionCode: 'TXN-0040',
    type: 'Farmer Registration',
    farmerName: 'Rosalinda Luna',
    barangay: 'San Isidro',
    subject: 'New farmer application',
    details: 'RSBSA registration with 1.2 ha farm area',
    submittedAt: '2025-05-21T14:30:00',
    submittedBy: 'Field Enumerator',
    status: 'pending',
  },
  {
    id: '3',
    transactionCode: 'TXN-0039',
    type: 'Program Enrollment',
    farmerName: 'Maria Santos',
    barangay: 'San Roque',
    subject: 'Rice Seed Subsidy',
    details: 'Enrollment for 2025 wet season planting',
    submittedAt: '2025-05-21T11:00:00',
    submittedBy: 'Barangay Official',
    status: 'under_review',
  },
  {
    id: '4',
    transactionCode: 'TXN-0038',
    type: 'Assistance Distribution',
    farmerName: 'Jose Rizal',
    barangay: 'Poblacion',
    subject: 'Livestock Support',
    details: '3 sacks animal feeds — DA grant allocation',
    amountPeso: 4200,
    submittedAt: '2025-05-20T16:45:00',
    submittedBy: 'Agriculture Officer',
    status: 'pending',
  },
  {
    id: '5',
    transactionCode: 'TXN-0037',
    type: 'Document Verification',
    farmerName: 'Pedro Garcia',
    barangay: 'Mabini',
    subject: 'Land tenure document',
    details: 'Barangay certification and farm lot sketch uploaded',
    submittedAt: '2025-05-20T10:20:00',
    submittedBy: 'Farmer (self-service)',
    status: 'pending',
  },
  {
    id: '6',
    transactionCode: 'TXN-0036',
    type: 'Crop Record',
    farmerName: 'Ana Reyes',
    barangay: 'San Isidro',
    subject: 'Harvest update — Eggplant',
    details: 'Marking plot as harvested; yield 420 kg reported',
    submittedAt: '2025-05-19T08:00:00',
    submittedBy: 'Agriculture Officer',
    status: 'approved',
  },
  {
    id: '7',
    transactionCode: 'TXN-0035',
    type: 'Assistance Distribution',
    farmerName: 'Lito Romano',
    barangay: 'San Roque',
    subject: 'Animal Feed Assistance',
    details: 'Duplicate request flagged — prior DIST-0006 exists',
    amountPeso: 2800,
    submittedAt: '2025-05-18T13:10:00',
    submittedBy: 'Barangay Official',
    status: 'rejected',
  },
  {
    id: '8',
    transactionCode: 'TXN-0034',
    type: 'Farmer Registration',
    farmerName: 'Danilo Valdez',
    barangay: 'San Roque',
    subject: 'New farmer application',
    details: 'Incomplete contact number — resubmission required',
    submittedAt: '2025-05-17T15:55:00',
    submittedBy: 'Field Enumerator',
    status: 'rejected',
  },
  {
    id: '9',
    transactionCode: 'TXN-0033',
    type: 'Program Enrollment',
    farmerName: 'Celia Mendoza',
    barangay: 'Mabini',
    subject: 'Corn Production Aid',
    details: 'Eligible per land area and crop plan review',
    submittedAt: '2025-05-16T09:40:00',
    submittedBy: 'Barangay Official',
    status: 'approved',
  },
  {
    id: '10',
    transactionCode: 'TXN-0032',
    type: 'Assistance Distribution',
    farmerName: 'Benito Silva',
    barangay: 'Poblacion',
    subject: 'Vegetable Seeds Program',
    details: '6 seed packets — barangay fund release approved',
    amountPeso: 950,
    submittedAt: '2025-05-15T11:25:00',
    submittedBy: 'Agriculture Officer',
    status: 'approved',
  },
];
